### PR TITLE
Up through dbw walkthrough

### PR DESCRIPTION
**Pull request by ryan-jonesford**
I've gone through the first two walk-throughs and this code is very close to what they have. The car in the simulator follows the waypoints using a controller and will correct itself if you take it off of automatic, drive around a little then put it back in automatic. I figured I could get the ball rolling with a commit to the baseline. It's okay to reject the commit if you are further along and think that your code should be here instead.

### CODE REVIEW

**Comment by ghost** [comment]
I went through the Q&A as well, even if I didn't code what's shown there yet. 
I checked what you wrote for both waypoint_updater and dbw_node and twist_controller (although these last two more quickly). Just a question from my side: is there a reason why on waypoint_updater, to find the nearest waypoint, the check if the waypoint is in front or behind the car is not performed?

**Comment by ryan-jonesford** [comment]
Must have missed it. It's not needed for it to work in the simulator so I guess I didn't notice that it wasn't there.

**Comment by ryan-jonesford** [comment]
I've added the check for the waypoint to be infront of the car

**Comment by gulshan216** [comment]
I have gone through all your changes. Just one question what is the reason for this change in ros/src/styx/server.py:
eventlet.wsgi.server(eventlet.listen(('', 4567)), app)
changed to 
eventlet.wsgi.server(eventlet.listen(('10.0.2.15', 4567)), app)

Is this because you are working in the VM?
All the other changes are OK with me

**Review by gulshan216 — COMMENTED** [review]
I have gone through all your changes. Just one question what is the reason for this change in ros/src/styx/server.py:
eventlet.wsgi.server(eventlet.listen(('', 4567)), app)
changed to
eventlet.wsgi.server(eventlet.listen(('10.0.2.15', 4567)), app)

Is this because you are working in the VM?
All the other changes are OK with me

**Comment by ghost** [comment]
Fine for me also. I want to merge your changes in this repo and then try to use them on mine to check them.

**Review by ghost — APPROVED** [review]
Everything Looks good. I will try it out.

**Review by gulshan216 — APPROVED** [review]
These changes are fine with me

**Pull request merged**
